import type { Portfolio } from "../portfolio-types";

export const ilhamPortfolio: Portfolio = {
  id: "ilham",
  fullName: "Ilham Ramdani",
  contact: {
    email: "skylinkbali@gmail.com",
    phone: "+62 878-6675-5564",
    location: "Selong, NTB, Indonesia",
    linkedin: "https://linkedin.com/in/ilham-ramdani-124b623b5",
  },
  hero: {
    headline: "HELLO",
    subheadline:
      "Senior Full Stack Software Engineer building scalable web and mobile applications with modern JavaScript, backend APIs, and cloud infrastructure.",
    role: "Senior Full Stack Software Engineer",
    avatarImage: undefined,
  },
  about: {
    heading: "Building scalable products across web, mobile, and cloud.",
    paragraphs: [
      "With 4 years of experience as a Senior Full Stack Software Engineer, I design, build, and maintain scalable web and mobile applications using React, Next.js, TypeScript, TailwindCSS, React Native, Flutter, Swift, and Kotlin.",
      "On the backend I ship REST and GraphQL APIs in Go, Node.js, Python, and Java, design event-driven systems with Kafka and RabbitMQ, and run cloud infrastructure on AWS, GCP, and Azure with Docker, Kubernetes, Terraform, GitHub Actions, and Jenkins.",
    ],
  },
  experiences: [
    {
      role: "Senior Software Engineer",
      company: "Navigate360",
      companyDomain: "navigate360.com",
      period: "May 2024 – Present",
      location: "Remote",
      description:
        "Owning full-stack delivery across React, Next.js, and TypeScript frontends plus Node.js and Go services, keeping UX and API contracts aligned across web and mobile.",
      achievements: [
        "Designed and versioned REST APIs with OpenAPI/Swagger in Go and Node.js, then consumed them via typed TypeScript SDKs in React clients.",
        "Shipped React Native and Flutter updates tied to the same backend endpoints so web and mobile stayed behaviorally consistent.",
        "Introduced GraphQL for read-heavy screens while maintaining REST fallbacks for older clients during rollout.",
        "Implemented Kafka streams for high-volume events and RabbitMQ workflows for fan-out jobs with ordering and retry requirements.",
        "Tuned PostgreSQL and Redis usage, tightened MongoDB schema conventions, and moved hot paths into caches to reduce latency.",
        "Containerized services with Docker, deployed on Kubernetes with proper readiness probes, and automated infrastructure via Terraform.",
        "Set up GitHub Actions and Jenkins pipelines for test/build/deploy, plus monitoring with Prometheus, Grafana, and ELK.",
        "Hardened security with OAuth2/JWT flows, RBAC middleware, TLS configuration, and cloud-based secrets management.",
      ],
    },
    {
      role: "Senior Full-Stack Developer",
      company: "Altermyth",
      companyDomain: "altermyth.com",
      period: "Aug 2023 – Mar 2024",
      location: "Remote",
      description:
        "Shipped product features end-to-end across React/Next.js frontends, Node.js and Go microservices, and mobile surfaces in Flutter and React Native.",
      achievements: [
        "Developed REST APIs and GraphQL resolvers feeding both web and mobile clients with predictable payloads.",
        "Introduced a Go microservice to handle performance-sensitive paths and reduce Node.js CPU spikes under load.",
        "Implemented RabbitMQ-based background jobs with retries, dead-letter queues, and idempotency keys.",
        "Used Kafka for analytics event streams and validated event schemas at producer boundaries.",
        "Optimized PostgreSQL schemas and queries, added Redis caching for hot reads, and safely evolved MongoDB documents.",
        "Ran containerized dev/prod parity with Docker and Kubernetes and kept environments reproducible with Terraform.",
        "Implemented CI/CD with GitHub Actions including Jest tests, integration coverage for Express routes, and security-focused TLS/auth hardening.",
      ],
    },
    {
      role: "Full-Stack Developer",
      company: "Nodeflux",
      companyDomain: "nodeflux.io",
      period: "Apr 2022 – Jun 2023",
      location: "Jakarta, Indonesia",
      description:
        "Built data-heavy dashboards and mobile-facing APIs across React/TypeScript, Node.js, Python, and Go services.",
      achievements: [
        "Delivered dashboard-style React views backed by Node.js and Python APIs with attention to pagination and payload size.",
        "Implemented Python services in Flask/Django for data processing workflows exposed via API gateways.",
        "Built a Go service for concurrency-heavy tasks using channels and worker pools, documented via OpenAPI for clients.",
        "Used Kafka and RabbitMQ for event-driven workflows, adding consumer retry logic and monitoring queue health.",
        "Designed relational schemas in PostgreSQL and MySQL, optimized queries, and used MongoDB and Redis where document or cache semantics fit better.",
        "Deployed services with Docker and Kubernetes, resolved rollout issues related to resource limits and restarts.",
        "Added CI coverage via Jenkins and GitHub Actions, using Jest, PyTest, and Postman collections for regression checks.",
        "Implemented OAuth2/JWT auth, RBAC for admin tools, and TLS configuration for stable mobile and web clients.",
      ],
    },
    {
      role: "Web Developer Intern",
      company: "Microsoft",
      companyDomain: "microsoft.com",
      period: "Apr 2021 – Mar 2022",
      location: "Remote",
      description:
        "Built and iterated on React/Next.js web features, contributed to Node.js and Python utilities, and learned large-repo workflows.",
      achievements: [
        "Implemented React and Next.js pages with SSR/CSR patterns and predictable data fetching behavior.",
        "Worked with Node.js Express APIs and Postman tests before wiring up UI flows.",
        "Contributed to a Python Flask utility service with simple, structured JSON endpoints.",
        "Wrote Jest tests and basic integration tests for core UI and API paths.",
        "Helped containerize dev setups using Docker and contributed to CI checks via GitHub Actions.",
        "Gained exposure to Azure deployment patterns, secrets management, TLS, and JWT/OAuth2 auth flows in frontends.",
      ],
    },
  ],
  projects: [
    {
      id: 1,
      title: "Cappen",
      description: "Digital agency website with high-end visuals and case study storytelling.",
      url: "https://www.cappen.com/",
      category: "Digital Agency",
      tech: ["React", "Next.js", "TypeScript"],
      featured: true,
    },
    {
      id: 2,
      title: "Casangelina",
      description: "Luxury hotel booking experience emphasizing imagery, storytelling, and smooth booking flows.",
      url: "https://www.casangelina.com/",
      category: "Hotel Booking",
      tech: ["React", "Next.js"],
      featured: true,
    },
    {
      id: 3,
      title: "Joni and Friends",
      description: "Nonprofit website focused on accessibility, content structure, and donation flows.",
      url: "https://www.joniandfriends.org/",
      category: "Nonprofit",
      tech: ["React", "CMS"],
      featured: true,
    },
    {
      id: 4,
      title: "Vissla",
      description: "Surf and lifestyle e‑commerce storefront with strong brand storytelling.",
      url: "https://www.vissla.com/",
      category: "E-commerce",
      tech: ["React", "E-commerce"],
      featured: false,
    },
    {
      id: 5,
      title: "BYND",
      description: "Brand and experience agency site focused on motion, layout, and portfolio presentation.",
      url: "https://www.bynd.com/",
      category: "Agency",
      tech: ["React", "Animations"],
      featured: false,
    },
    {
      id: 6,
      title: "Tangent",
      description: "Design and technology agency site with a focus on case studies and storytelling.",
      url: "https://www.tangent.co.uk/",
      category: "Digital Agency",
      tech: ["React", "Next.js"],
      featured: true,
    },
  ],
  theme: "warm",
  sections: ["hero", "about", "experience", "projects", "contact"],
  heroVariant: "bento",
  projectsVariant: "grid",
  experienceVariant: "default",
  contactVariant: "default",
  bento: {
    globeRegion: "sea",
  },
};

