import type { Portfolio } from "../portfolio-types";

export const kevinWpPortfolio: Portfolio = {
  id: "kevin-wp",
  fullName: "Kevin Nguyen",
  contact: {
    email: "kevinnguyendev0312@gmail.com",
    phone: "(341) 204-0320",
    location: "Union City, CA",
    timezone: "America/Los_Angeles",
  },
  hero: {
    headline: "HELLO",
    subheadline:
      "Senior WordPress developer shipping enterprise themes, plugins, and headless stacks—WooCommerce, Gutenberg, performance, and security at scale.",
    role: "Senior WordPress Developer",
  },
  about: {
    heading: "WordPress at scale—from custom themes to headless and commerce.",
    paragraphs: [
      "Senior full-stack developer with 11 years of progressive experience. I specialize in WordPress, PHP, and scalable e-commerce—alongside Shopify, Liquid, React, Angular, and Vue when projects demand it. I’ve improved user engagement by up to ~30%, cut operational costs ~20% through automation, and boosted online sales up to ~25% on select programs by shipping full-cycle web applications with a focus on seamless customer experiences.",
      "Core delivery: custom WordPress themes and plugins (OOP, SOLID), headless WordPress with React and the WP REST API, WooCommerce (custom checkout, subscriptions, payments), Gutenberg blocks, ACF, Elementor, WP-CLI, and multisite. I pair that with Node.js/Express, REST and GraphQL APIs, and data layers across MySQL, PostgreSQL, and MongoDB. Responsive web design and progressive web apps (PWAs) for cross-device experiences.",
      "Infrastructure and quality: AWS (EC2, S3), Heroku, Docker, CI/CD (GitHub Actions, Jenkins, Travis CI), Redis, Memcached, Cloudflare, and CDN strategies. Version control with Git, GitHub, and Bitbucket. Testing with Selenium, Jest, Mocha, Chai, and Jasmine; monitoring and security with New Relic, Cloudflare, and OWASP-minded practices.",
      "Bachelor of Science in Computer Science, UC San Diego (2012–2016).",
    ],
  },
  experiences: [
    {
      role: "Senior WordPress Developer",
      company: "The Good Project",
      companyDomain: "thegoodproject.com",
      period: "Aug 2023 — Aug 2025",
      description:
        "Led enterprise WordPress platforms: custom themes and plugins, headless React + WP REST API, WooCommerce checkout and subscriptions, Gutenberg blocks, and performance/security at scale.",
      achievements: [
        "Delivered end-to-end WordPress platforms that improved engagement by ~35% through tailored themes, plugins, and integrations.",
        "Architected headless solutions with React and WP REST API for faster rendering and scalability under high traffic.",
        "Cut page load times ~50% via Redis, CDN, and object caching aligned with Core Web Vitals.",
        "Built custom Gutenberg blocks and WooCommerce flows (subscriptions, third-party integrations) lifting conversion ~20%.",
        "Reduced security exposure ~95% via hardening, JWT/OAuth2, and secure API patterns; integrated Google Analytics 4 and server-side tracking for data-driven optimization.",
        "Ran Agile sprint planning, mentored junior developers, and established coding standards to lift team productivity and code quality.",
      ],
    },
    {
      role: "SEO Automation Engineer (WordPress Focus)",
      company: "Cubework",
      companyDomain: "cubework.com",
      period: "Jan 2020 — Mar 2024",
      description:
        "Built WordPress-centric SEO automation: plugins for dynamic metadata, API-driven marketing and analytics integrations, and migrations to modern AWS-hosted WordPress.",
      achievements: [
        "Improved organic traffic ~45% with SEO automation plugins and metadata workflows.",
        "Reduced server response times ~60% at peak via query tuning, full-page cache, Redis, and CDN.",
        "Migrated legacy CMS to WordPress on AWS with ~$500K annual cost savings.",
        "Automated SEO with Python and Selenium; lifted keyword rankings ~30% in three months.",
        "Built real-time dashboards with the Google Analytics API to monitor SEO performance and campaign effectiveness.",
        "Conducted technical SEO audits and collaborated with content teams to improve site architecture and engagement metrics.",
      ],
    },
    {
      role: "Senior Full Stack Engineer (WordPress)",
      company: "Kirusoft",
      companyDomain: "kirusoft.com",
      period: "Jan 2021 — Aug 2023",
      description:
        "Owned WordPress and WooCommerce rewrites, CRM and payment integrations, team leadership, and CI/CD for reliable releases.",
      achievements: [
        "Redeveloped WordPress/WooCommerce platforms: engagement ~35% up, conversion ~28% up.",
        "Shipped custom plugins for CRM, payments, and APIs; led a four-person team with ~95% on-time delivery.",
        "Scaled for ~200% more concurrent users via performance tuning and caching.",
        "Refactored legacy code into modular architectures; implemented CI/CD to shorten release cycles and reduce downtime.",
        "Strengthened security with OWASP-aligned practices, secure authentication, and regular vulnerability assessments.",
      ],
    },
    {
      role: "Senior Frontend Developer (WordPress Ecosystem)",
      company: "Techyscouts",
      companyDomain: "techyscouts.com",
      period: "May 2019 — Dec 2020",
      description:
        "Built responsive WordPress frontends with React and headless patterns; migrated themes to Gutenberg and partnered with design on UX.",
      achievements: [
        "Delivered headless and classic WordPress frontends with React; migrated legacy themes to Gutenberg.",
        "Cut bounce rate ~50% through UX collaboration and performance work (Core Web Vitals, lazy loading).",
        "Used Redux, REST APIs, and OWASP-minded frontend practices for secure, dynamic experiences.",
        "Improved cross-browser compatibility and mobile responsiveness across multiple WordPress properties.",
      ],
    },
    {
      role: "WordPress Developer",
      company: "Dyode",
      companyDomain: "dyode.com",
      period: "Mar 2016 — May 2019",
      description:
        "Custom themes, WooCommerce, plugins, and SEO for client sites—payment integrations, performance, and maintainable theme frameworks.",
      achievements: [
        "Increased client revenue ~20% through WooCommerce and theme customization.",
        "Built plugins to replace fragile third-party dependencies; reduced cart abandonment ~15% on checkout work.",
        "Cut delivery time ~25% with reusable frameworks; improved organic visibility ~30% with schema and SEO fundamentals.",
        "Supported WordPress migrations, upgrades, and maintenance for enterprise clients.",
        "Partnered with designers and stakeholders to ship polished, user-focused experiences.",
      ],
    },
  ],
  projects: [
    {
      id: 1,
      title: "Crafted NY",
      description:
        "Digital agency site—polished brand and portfolio experience (WordPress on WP Engine).",
      url: "https://www.craftedny.com/",
      category: "Digital Agency",
      tech: ["WordPress", "WP Engine", "Agency"],
      featured: true,
    },
    {
      id: 2,
      title: "Pound & Grain",
      description: "Digital agency with bold creative and case-study driven storytelling.",
      url: "https://poundandgrain.com/",
      category: "Digital Agency",
      tech: ["WordPress", "Agency"],
      featured: true,
    },
    {
      id: 3,
      title: "Flightpath",
      description: "Digital agency focused on strategy, design, and development for growth-focused brands.",
      url: "https://www.flightpath.com/",
      category: "Digital Agency",
      tech: ["WordPress", "Agency"],
      featured: true,
    },
    {
      id: 4,
      title: "Maxobiz",
      description: "Design-led agency build with rich motion (GSAP) and PHP-driven WordPress patterns.",
      url: "https://www.maxobiz.com/",
      category: "Design Agency",
      tech: ["PHP", "GSAP", "WordPress"],
      featured: false,
    },
    {
      id: 5,
      title: "AvaTrade",
      description: "Global forex and CFD trading platform with high-scale PHP-backed experiences.",
      url: "https://www.avatrade.com/",
      category: "Forex / Fintech",
      tech: ["PHP", "Trading Platform"],
      featured: true,
    },
    {
      id: 6,
      title: "GIS Cloud",
      description: "Cloud GIS software product marketing and app ecosystem.",
      url: "https://www.giscloud.com/",
      category: "Cloud Software",
      tech: ["Cloud", "SaaS"],
      featured: false,
    },
    {
      id: 7,
      title: "Aventus",
      description: "Cryptocurrency and blockchain project presence and product narrative.",
      url: "https://www.aventus.io/",
      category: "Cryptocurrency",
      tech: ["Web3", "Blockchain"],
      featured: false,
    },
    {
      id: 8,
      title: "NNC Solutions",
      description: "Telecommunications solutions provider—corporate site and service positioning (EN).",
      url: "https://nncsolutions.com/en/",
      category: "Telecommunications",
      tech: ["Corporate", "Multilingual"],
      featured: false,
    },
  ],
  theme: "warm",
  sections: ["hero", "about", "projects", "experience", "contact"],
  heroVariant: "bento",
  projectsVariant: "grid",
  experienceVariant: "default",
  contactVariant: "default",
  bento: {
    globeRegion: "us",
  },
};
